### PR TITLE
Task 7

### PR DESCRIPTION
**Pull request by svetlanagorchanina**
**EVALUATION CRITERIA**

- authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file
- import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda.
- update client application to send Authorization: Basic authorization_token header on import.

**Additional**

- Client application should display alerts for the responses in 401 and 403 HTTP statuses.

---

FE App: https://d12r4l4twrn36b.cloudfront.net/
FE PR: https://github.com/svetlanagorchanina/nodejs-aws-fe/pull/5
Import API: `GET` https://spj4lfm776.execute-api.eu-west-1.amazonaws.com/dev/import?name=test.csv

---

Notes:
- `localStorage.setItem('authorization_token', 'c3ZldGxhbmFnb3JjaGFuaW5hOlRFU1RfUEFTU1dPUkQ=')`
- test csv: [test.csv.zip](https://github.com/svetlanagorchanina/nodejs-aws-be/files/5578342/test.csv.zip)

### CODE REVIEW

**Comment by Max-Korsakov** [comment]
Why application doesn't set a token to the localstorage?

**Comment by svetlanagorchanina** [comment]
> Why application doesn't set a token to the localstorage?

You mean hard-coded token?
If so it's not secure and didn't find such requirements in task description. If you think it must have, please give me a notice.

**Comment by Max-Korsakov** [comment]
I believe, makes sense to set the token to the .env file, then set it to the local storage with a hook on the front end.

'Client should get authorization_token value from browser localStorage'. How should I set it there for the check, with my hands?)

**Comment by svetlanagorchanina** [comment]
> I believe, makes sense to set the token to the .env file, then set it to the local storage with a hook on the front end.

.env file with credentials should not be committed, and again security issue + didn't find such requirements

> 'Client should get authorization_token value from browser localStorage'. How should I set it there for the check, with my hands?)

1. You can execute the next command inside dev tool console
```
localStorage.setItem('authorization_token', 'c3ZldGxhbmFnb3JjaGFuaW5hOlRFU1RfUEFTU1dPUkQ=')
``` 
2. You can open dev tool, navigate to "Application" tab, select "Local Storage" menu item and manually add `key:authorization_token`, `value: c3ZldGxhbmFnb3JjaGFuaW5hOlRFU1RfUEFTU1dPUkQ=`

> 'Client should get authorization_token value from browser localStorage'.

I reckon it means, that client app should get token from localStorage, as it actually works now (https://github.com/svetlanagorchanina/nodejs-aws-fe/pull/5/files#diff-24432b1f8209e7604bd55964d5a41321169ae306bbaa65064d4ed9a03fdd4d2fR40-R43).

**Pull request merged**
